apiVersion: v1
kind: ReplicationController
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:4.6.2-3
        imagePullPolicy: Always
        env:
          - name: PMA_ARBITRARY
            value: '1'
        ports:
          - name: http
            containerPort: 80
