
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: redis
spec:
  containers:
  - name: redis
    image: appscode/postgres:redis
    command:
    - "redis-server"
  volumeMounts:
  - mountPath: /data
    name: redis-store
  volumes:
  - name: redis-store
    hostPath:
      path: /opt/redis
 imagePullSecrets:
    - name: myregistrykey