apiVersion: v1
kind: Service
metadata: 
  name: influxdb
  labels: 
    name: influxdb
spec: 
  ports: 
    - name: port1
      port: 8083
      protocol: TCP
    - name: port2
      port: 8086
      protocol: TCP
  selector: 
    name: influxdb